name: Update README

# "on" defines when the workflow should run.
# schedule: runs once a day at midnight (UTC).
# workflow_dispatch: allows you to trigger it manually in the Actions tab.
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run the update script
      - name: Update README
        run: node update-readme.js

      # 5. Commit and push changes back to GitHub
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "chore: updated README with dynamic data"
          git push
